# This workflow will publish npm package on release
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      CPATH="/framefusion/.framefusion-ffmpeg/ffmpeg/include/"
      PKG_CONFIG_PATH="/framefusion/.framefusion-ffmpeg/ffmpeg/lib/pkgconfig/"
    defaults:
      run:
        working-directory: /framefusion
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: sudo ./scripts/install_beamcoder_dependencies.sh
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
