# This workflow will publish npm package on release
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      CPATH: /tmp/framefusion/.framefusion-ffmpeg/ffmpeg/include/
      PKG_CONFIG_PATH: /tmp/framefusion/.framefusion-ffmpeg/ffmpeg/lib/pkgconfig/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: mkdir /tmp/framefusion
      - run: cp -r . /tmp/framefusion
      - run: sudo ./scripts/install_beamcoder_dependencies.sh
        working-directory: /tmp/framefusion
      - run: yarn install --frozen-lockfile
        working-directory: /tmp/framefusion
      - run: yarn build
        working-directory: /tmp/framefusion
      - run: yarn publish
        working-directory: /tmp/framefusion
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
